[project]
name = "edu-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "openai",
    "python-dotenv",
    "pandas",
    "PyPDF2",
    "chromadb",
    "typing",
    "whisper",
    "Markdown"
]
